(function(){
'use strict';
const $=s=>document.querySelector(s);
const app=$('#app');
const toastEl=$('#toast');
const money=n=>'₹'+Number(n||0).toFixed(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imageUrls={
 'restaurant-south':'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80',
 'restaurant-indian':'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80',
 'restaurant-cafe':'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=900&q=80',
 'restaurant-generic':'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80',
 'masala-dosa':'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=900&q=80',
 'idli':'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=80',
 'veg-meals':'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',
 'biryani':'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=900&q=80',
 'paneer':'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=900&q=80',
 'naan':'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',
 'pizza':'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',
 'burger':'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
 'lime':'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=900&q=80',
 'special':'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'
};
const img=n=>imageUrls[n]||`assets/${n}.svg`;
const seedRestaurants=[
 {id:'r1',name:'Anup South Kitchen',city:'Chennai',rating:4.7,type:'South Indian',image:'restaurant-south',menu:[
  {id:'m1',name:'Masala Dosa',price:80,desc:'Crispy dosa with potato masala and chutney.',image:'masala-dosa'},
  {id:'m2',name:'Idli Sambar',price:60,desc:'Soft idlis served with sambar and chutney.',image:'idli'},
  {id:'m3',name:'Veg Meals',price:150,desc:'Rice, sambar, rasam, poriyal and curd.',image:'veg-meals'}]},
 {id:'r2',name:'Bistro Spice',city:'Coimbatore',rating:4.6,type:'Indian',image:'restaurant-indian',menu:[
  {id:'m4',name:'Chicken Biryani',price:220,desc:'Aromatic basmati rice with spiced chicken.',image:'biryani'},
  {id:'m5',name:'Paneer Butter Masala',price:180,desc:'Paneer cooked in a creamy tomato gravy.',image:'paneer'},
  {id:'m6',name:'Butter Naan',price:45,desc:'Soft naan finished with butter.',image:'naan'}]},
 {id:'r3',name:'Bistro Cafe',city:'Madurai',rating:4.5,type:'Cafe',image:'restaurant-cafe',menu:[
  {id:'m7',name:'Veg Pizza',price:190,desc:'Cheesy pizza with fresh vegetables.',image:'pizza'},
  {id:'m8',name:'Veg Burger',price:140,desc:'Crispy veggie patty with fresh salad.',image:'burger'},
  {id:'m9',name:'Fresh Lime',price:50,desc:'Refreshing lime drink.',image:'lime'}]}
];
let restaurants=JSON.parse(localStorage.getItem('anup_restaurants')||'null')||seedRestaurants;
let bills=JSON.parse(localStorage.getItem('anup_bills')||'[]');
let state={page:'login',role:'customer',restaurantId:null,cart:[],lastBill:null};
function save(){localStorage.setItem('anup_restaurants',JSON.stringify(restaurants));localStorage.setItem('anup_bills',JSON.stringify(bills));}
function notify(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toastEl.classList.remove('show'),1800)}
function go(page,extra={}){state={...state,...extra,page};render();window.scrollTo(0,0)}
function nav(){return `<div class="topbar"><div class="brand"><div class="logo">A</div><div><h1>ANUPBistro</h1><small>Restaurant Management</small></div></div><div class="nav-actions">${state.page!=='login'?'<button class="nav-btn" data-action="home">⌂ Home</button>':''}${state.page!=='login'&&state.page!=='customer'?'<button class="nav-btn" data-action="back">← Back</button>':''}</div></div>`}
function render(){
 if(state.page==='login') return renderLogin();
 if(state.page==='customer') return renderCustomer();
 if(state.page==='menu') return renderMenu();
 if(state.page==='bill') return renderBill();
 if(state.page==='admin') return renderAdmin();
 go('login');
}
function renderLogin(){app.innerHTML=`<div class="phone"><main class="page"><div class="hero"><div class="hero-logo">WELCOME TO</div><h2>ANUPBistro</h2><p>Simple restaurant ordering and management in one mobile app.</p></div><div class="form-card"><div class="form-group"><label>Name</label><input id="loginName" class="input" value="Guest" placeholder="Enter your name"></div><div class="form-group"><label>Choose access</label><div class="role-switch"><button class="role ${state.role==='customer'?'active':''}" data-role="customer">Customer</button><button class="role ${state.role==='admin'?'active':''}" data-role="admin">Admin</button></div></div><button class="btn btn-primary" data-action="login">Continue</button><p class="muted small" style="margin:12px 0 0;text-align:center">Demo app • No password required</p></div></main></div>`}
function renderCustomer(){app.innerHTML=`<div class="phone"><main class="page">${nav()}<div class="hero"><div class="hero-logo">CUSTOMER</div><h2>Choose a restaurant</h2><p>Select a restaurant to view its menu and add items to your bill.</p></div><div class="section-title"><h3>Restaurants</h3><span>${restaurants.length} available</span></div><div class="grid">${restaurants.map(r=>`<article class="restaurant-card"><img src="${img(r.image)}" alt="${esc(r.name)}"><div class="restaurant-body"><h3>${esc(r.name)}</h3><p>${esc(r.type)} • ${esc(r.city)}</p><div class="restaurant-meta"><span>★ ${r.rating}</span><span>Open now</span></div><button class="open-btn" data-restaurant="${r.id}">View Menu</button></div></article>`).join('')}</div></main>${state.cart.length?cartBar():''}</div>`}
function cartBar(){return `<div class="sticky-cart"><div class="cart-text"><small>${cartCount()} items</small><strong>${money(cartTotal())}</strong></div><button class="btn btn-primary btn-small" data-action="bill">View Bill</button></div>`}
function getRestaurant(){return restaurants.find(r=>r.id===state.restaurantId)}
function renderMenu(){const r=getRestaurant();if(!r)return go('customer');app.innerHTML=`<div class="phone"><main class="page">${nav()}<div class="hero"><div class="hero-logo">${esc(r.type).toUpperCase()}</div><h2>${esc(r.name)}</h2><p>${esc(r.city)} • ★ ${r.rating}</p></div><div class="section-title"><h3>Menu</h3><span>${r.menu.length} items</span></div><div class="menu-list">${r.menu.map(m=>`<article class="menu-card"><img src="${img(m.image)}" alt="${esc(m.name)}"><div class="menu-info"><h4>${esc(m.name)}</h4><p>${esc(m.desc)}</p><div class="price">${money(m.price)}</div><button class="add-btn" data-add="${m.id}">+ Add</button></div></article>`).join('')}</div></main>${state.cart.length?cartBar():''}</div>`}
function cartCount(){return state.cart.reduce((a,x)=>a+x.qty,0)}
function cartTotal(){return state.cart.reduce((a,x)=>a+x.price*x.qty,0)}
function renderBill(){if(state.lastBill)return renderSuccess();app.innerHTML=`<div class="phone"><main class="page">${nav()}<div class="hero"><div class="hero-logo">BILL PROCESSING</div><h2>Your Bill</h2><p>Review your items and confirm the order.</p></div><div class="panel">${state.cart.length?state.cart.map((x,i)=>`<div class="bill-item"><div><strong>${esc(x.name)}</strong><div class="muted small">${money(x.price)} each</div></div><div style="text-align:right"><div class="qty"><button data-minus="${i}">−</button><strong>${x.qty}</strong><button data-plus="${i}">+</button></div><div class="small" style="margin-top:5px">${money(x.price*x.qty)}</div></div></div>`).join(''):'<div class="empty">Your cart is empty.</div>'}<div class="bill-summary"><div class="sum-row"><span>Subtotal</span><strong>${money(cartTotal())}</strong></div><div class="sum-row"><span>GST (5%)</span><strong>${money(cartTotal()*.05)}</strong></div><div class="sum-row total"><span>Total</span><span>${money(cartTotal()*1.05)}</span></div></div><button class="btn btn-primary" style="margin-top:14px" data-action="pay" ${state.cart.length?'':'disabled'}>Confirm & Generate Bill</button></div></main></div>`}
function renderSuccess(){const b=state.lastBill;app.innerHTML=`<div class="phone"><main class="page">${nav()}<div class="panel success"><div class="success-icon">✓</div><h2>Order Confirmed</h2><p class="muted">Bill #${esc(b.id)} has been saved.</p><div class="panel" style="margin-top:18px;text-align:left;background:#0b172a"><div class="sum-row"><span>Restaurant</span><strong>${esc(b.restaurant)}</strong></div><div class="sum-row"><span>Items</span><strong>${b.items.reduce((a,x)=>a+x.qty,0)}</strong></div><div class="sum-row total"><span>Paid</span><span>${money(b.total)}</span></div></div><button class="btn btn-primary" style="margin-top:15px" data-action="neworder">New Order</button></div></main></div>`}
function renderAdmin(){const total=bills.reduce((a,b)=>a+b.total,0),today=new Date().toDateString(),todayBills=bills.filter(b=>new Date(b.createdAt).toDateString()===today);app.innerHTML=`<div class="phone"><main class="page">${nav()}<div class="hero"><div class="hero-logo">ADMIN</div><h2>Dashboard</h2><p>Manage restaurants, bills and daily transactions.</p></div><div class="admin-grid"><div class="stat"><small>Restaurants</small><strong>${restaurants.length}</strong></div><div class="stat"><small>Total Bills</small><strong>${bills.length}</strong></div><div class="stat"><small>Today's Bills</small><strong>${todayBills.length}</strong></div><div class="stat"><small>Total Sales</small><strong>${money(total)}</strong></div></div><div class="admin-section"><button class="btn btn-primary" data-action="addrestaurant">+ Add Restaurant</button></div><div class="admin-section panel"><div class="section-title" style="margin-top:0"><h3>Daily Transactions</h3><span>${new Date().toLocaleDateString()}</span></div>${todayBills.length?todayBills.slice().reverse().map(tx=>txCard(tx)).join(''):'<div class="empty">No transactions today.</div>'}</div><div class="admin-section panel"><div class="section-title" style="margin-top:0"><h3>All Bill Details</h3><span>${bills.length} bills</span></div>${bills.length?bills.slice().reverse().map(tx=>txCard(tx)).join(''):'<div class="empty">No bills yet.</div>'}</div></main></div>`}
function txCard(b){return `<div class="transaction"><div class="line"><strong>#${esc(b.id)}</strong><strong>${money(b.total)}</strong></div><div class="line" style="margin-top:5px"><small>${esc(b.restaurant)}</small><small>${new Date(b.createdAt).toLocaleString()}</small></div><div class="small" style="margin-top:8px">${b.items.map(x=>esc(x.name)+' × '+x.qty).join(', ')}</div></div>`}
function addItem(id){const r=getRestaurant();const m=r?.menu.find(x=>x.id===id);if(!m)return;const existing=state.cart.find(x=>x.id===m.id);if(existing)existing.qty++;else state.cart.push({...m,qty:1,restaurantId:r.id,restaurant:r.name});notify(m.name+' added');render()}
function changeQty(i,d){if(!state.cart[i])return;state.cart[i].qty+=d;if(state.cart[i].qty<=0)state.cart.splice(i,1);render()}
function completeBill(){if(!state.cart.length)return;const r=state.cart[0].restaurant;const b={id:'B'+Date.now().toString().slice(-7),restaurant:r,items:state.cart.map(x=>({name:x.name,price:x.price,qty:x.qty})),subtotal:cartTotal(),gst:cartTotal()*.05,total:cartTotal()*1.05,createdAt:new Date().toISOString()};bills.push(b);save();state.lastBill=b;state.cart=[];render();}
function showAddRestaurant(){const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<div class="modal"><div class="close-row"><h3>Add Restaurant</h3><button class="close" data-close>×</button></div><div class="form-group"><label>Restaurant name</label><input id="newRName" class="input" placeholder="e.g. Anup Family Restaurant"></div><div class="form-group"><label>City</label><input id="newRCity" class="input" placeholder="Chennai"></div><div class="form-group"><label>Type</label><input id="newRType" class="input" placeholder="Indian / Cafe"></div><div class="form-group"><label>Rating</label><input id="newRRating" class="input" type="number" min="1" max="5" step="0.1" value="4.5"></div><button class="btn btn-primary" data-save-restaurant>Save Restaurant</button></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('[data-close]'))modal.remove();if(e.target.closest('[data-save-restaurant]')){const name=$('#newRName').value.trim();const city=$('#newRCity').value.trim()||'Chennai';const type=$('#newRType').value.trim()||'Restaurant';const rating=Math.min(5,Math.max(1,Number($('#newRRating').value)||4.5));if(!name){notify('Enter restaurant name');return}restaurants.push({id:'r'+Date.now(),name,city,type,rating,image:'restaurant-generic',menu:[{id:'m'+Date.now(),name:'Chef Special',price:120,desc:'Add more menu items in the source code.',image:'special'}]});save();modal.remove();notify('Restaurant added');render()}})}
app.addEventListener('click',e=>{const role=e.target.closest('[data-role]');if(role){state.role=role.dataset.role;render();return}const r=e.target.closest('[data-restaurant]');if(r){state.restaurantId=r.dataset.restaurant;state.cart=[];state.lastBill=null;go('menu');return}const add=e.target.closest('[data-add]');if(add){addItem(add.dataset.add);return}const minus=e.target.closest('[data-minus]');if(minus){changeQty(Number(minus.dataset.minus),-1);return}const plus=e.target.closest('[data-plus]');if(plus){changeQty(Number(plus.dataset.plus),1);return}const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='login'){if(state.role==='admin')go('admin');else go('customer');return}if(a==='home'){state.cart=[];state.lastBill=null;go(state.role==='admin'?'admin':'customer');return}if(a==='back'){if(state.page==='menu')go('customer');else if(state.page==='bill')go('menu');else if(state.page==='admin')go('login');return}if(a==='bill'){state.lastBill=null;go('bill');return}if(a==='pay'){completeBill();return}if(a==='neworder'){state.lastBill=null;go('customer');return}if(a==='addrestaurant'){showAddRestaurant();return}});
render();
})();
